### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by L0Pope** [L0Pope/groupproject-team4#3]
Issue 3: Lastly, we had original plans for a leaderboard but we ended up running out of time for it as well so we had an empty leaderboard that didn't save data. I will need to go into the displays class in order to change the leaderboard and implement it. In order to implement this I need to figure out a way to save data efficiently and possibly even across game starts. If it were python I would use some text files and write to them so I need to figure it out for Java.

**Comment by onzfonz** [comment]
Work on this one.
